# Generated by Django 4.2 on 2023-04-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
