# Generated by Django 4.2 on 2023-04-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='joined_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
