# Generated by Django 4.2 on 2023-04-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_posts_created_on_posts_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='desc',
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
