# Generated by Django 4.2 on 2023-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_posts_desc_alter_posts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
